'use client';

import { useState } from 'react';
import { generatePropertyDescription } from '@/lib/utils/descriptionGenerator';

export default function PropertyForm() {
  const [formData, setFormData] = useState({
    title: '',
    offerType: 'sale' as 'sale' | 'rent',
    propertyType: 'apartment',
    price: '',
    city: '',
    district: '',
    areaUsable: '',
    rooms: '',
    floor: '',
    description: '',
  });

  const [features, setFeatures] = useState({
    hasBalcony: false,
    hasTerrace: false,
    hasLoggia: false,
    hasElevator: false,
    hasParking: false,
    hasGarage: false,
    hasBasement: false,
    hasPool: false,
    hasSauna: false,
    hasAirConditioning: false,
    isRenovated: false,
  });

  // Generovanie popisu pri zmene parametrov
  const handleAutoGenerateDescription = () => {
    if (!formData.title || !formData.city || !formData.areaUsable) {
      alert('Pre vygenerovanie popisu vyplňte prosím Názov, Lokalitu a Úžitkovú plochu.');
      return;
    }

    const generatedText = generatePropertyDescription({
      title: formData.title,
      offerType: formData.offerType,
      propertyType: formData.propertyType,
      city: formData.city,
      district: formData.district,
      price: Number(formData.price),
      areaUsable: Number(formData.areaUsable),
      rooms: formData.rooms ? Number(formData.rooms) : undefined,
      floor: formData.floor ? Number(formData.floor) : undefined,
      features,
    });

    setFormData((prev) => ({ ...prev, description: generatedText }));
  };

  return (
    <form className="max-w-4xl mx-auto bg-white p-8 rounded-2xl shadow-md border border-gray-200 space-y-6">
      <h2 className="text-2xl font-bold text-gray-800">Pridať novú nehnuteľnosť</h2>

      {/* Základné údaje */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium mb-1">Názov ponuky *</label>
          <input
            type="text"
            value={formData.title}
            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            placeholder="Napr. Slnečný 3-izbový byt v centre"
            className="w-full p-2.5 border rounded-lg"
            required
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Mesto / Lokalita *</label>
          <input
            type="text"
            value={formData.city}
            onChange={(e) => setFormData({ ...formData, city: e.target.value })}
            placeholder="Napr. Trnava"
            className="w-full p-2.5 border rounded-lg"
            required
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Cena (€) *</label>
          <input
            type="number"
            value={formData.price}
            onChange={(e) => setFormData({ ...formData, price: e.target.value })}
            className="w-full p-2.5 border rounded-lg"
            required
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1">Úžitková plocha (m²) *</label>
          <input
            type="number"
            value={formData.areaUsable}
            onChange={(e) => setFormData({ ...formData, areaUsable: e.target.value })}
            className="w-full p-2.5 border rounded-lg"
            required
          />
        </div>
      </div>

      {/* Checkboxy pre vybavenie */}
      <div>
        <h3 className="text-md font-semibold text-gray-700 mb-3">Vybavenie a vlastnosti (pre automatický popis):</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 bg-gray-50 p-4 rounded-xl border">
          {Object.entries({
            hasBalcony: 'Balkón',
            hasTerrace: 'Terasa',
            hasLoggia: 'Lógia',
            hasElevator: 'Výťah',
            hasParking: 'Parkovacie miesto',
            hasGarage: 'Garáž',
            hasBasement: 'Pivnica',
            hasAirConditioning: 'Klimatizácia',
            hasPool: 'Bazén',
            hasSauna: 'Sauna',
            isRenovated: 'Kompletná rekonštrukcia',
          }).map(([key, label]) => (
            <label key={key} className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                checked={features[key as keyof typeof features]}
                onChange={(e) =>
                  setFeatures({ ...features, [key]: e.target.checked })
                }
                className="rounded text-[#E32328] focus:ring-[#E32328]"
              />
              {label}
            </label>
          ))}
        </div>
      </div>

      {/* Tlačidlo na vygenerovanie textu */}
      <div className="flex justify-between items-center">
        <label className="block text-sm font-medium">Popis nehnuteľnosti</label>
        <button
          type="button"
          onClick={handleAutoGenerateDescription}
          className="bg-[#108243] hover:bg-[#0d6b37] text-white text-sm font-medium px-4 py-2 rounded-lg transition shadow flex items-center gap-2"
        >
          ✨ Vygenerovať popis z vlastností
        </button>
      </div>

      {/* Textarea pre editáciu popisu */}
      <textarea
        rows={8}
        value={formData.description}
        onChange={(e) => setFormData({ ...formData, description: e.target.value })}
        placeholder="Popis sa automaticky vygeneruje kliknutím na tlačidlo vyššie, alebo ho môžete napísať ručne..."
        className="w-full p-3 border rounded-lg font-sans text-sm focus:ring-2 focus:ring-[#E32328] focus:outline-none"
      ></textarea>

      <button
        type="submit"
        className="w-full bg-[#E32328] hover:bg-[#c81e22] text-white font-bold py-3 rounded-xl transition"
      >
        Uložiť nehnuteľnosť
      </button>
    </form>
  );
}